---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./awair-exporter/ks.yaml
  - ./alloy/ks.yaml
  - ./blackbox-exporter/ks.yaml
  - ./grafana/ks.yaml
  - ./graphite-exporter/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./kube-state-metrics/ks.yaml
  - ./loki/ks.yaml
  - ./node-exporter/ks.yaml
  - ./scrape-configs/ks.yaml
  - ./thanos/ks.yaml

components:
  - ../../components/privileged-namespace
  - ../../components/flux/alerts
