[settings]
pipx_uvx = true

[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }

[tools]
"python" = "3.14.2"
"uv" = "latest"
"pipx:makejinja" = "2.8.2"
"pipx:flux-local" = "8.1.0"
"aqua:budimanjojo/talhelper" = "3.1.3"
"aqua:cilium/cilium-cli" = "0.18.3"
"aqua:cli/cli" = "2.86.0"
"aqua:cue-lang/cue" = "0.15.4"
"aqua:FiloSottile/age" = "1.3.1"
"aqua:fluxcd/flux2" = "2.5.1"
"aqua:getsops/sops" = "3.11.0"
"aqua:go-task/task" = "3.48.0"
"aqua:helm/helm" = "4.1.0"
"aqua:helmfile/helmfile" = "1.2.3"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.32.3"
"aqua:mikefarah/yq" = "4.52.2"
