[settings]
pipx_uvx = true

[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }

[tools]
"aqua:astral-sh/uv" = ["latest"]
"aqua:google/yamlfmt" = ["latest"]
"aqua:kubernetes-sigs/kustomize" = ["latest"]
"aqua:fluxcd/flux2" = ["latest"]
"pipx:flux-local" = ["latest"]
