---
- name: Ensure Docker service is enabled and running
  systemd:
    name: docker
    enabled: true
    state: started

- name: Create systemd service for node-exporter
  template:
    src: node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
  notify: restart node-exporter service

- name: Enable and start the node-exporter service
  systemd:
    name: node-exporter
    enabled: true
    state: started
    daemon_reload: yes
