---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./atuin/ks.yaml
  # - ./bambustatus-streamer/ks.yaml
  - ./bluesky-pds/ks.yaml
  - ./echo-server/ks.yaml
  - ./minecraft-cpw/ks.yaml
  - ./minecraft-sf5/ks.yaml
  - ./minecraft-stoneblock/ks.yaml
  - ./minecraft-vanilla/ks.yaml
  - ./owncast/ks.yaml
  - ./paperless/ks.yaml
  - ./thelounge/ks.yaml
