$ANSIBLE_VAULT;1.1;AES256
66336663653233333665383563616130313136366133306633333763343932376334343331343763
3264633665656564346232383263616235386331326135330a616262633662653365623263373939
65653231663164303564343232386361666434376633386235373262323934366266306338386532
6130663864356461320a653565633361336238323534653862363931653239633838353062646235
65353039663061343833636364383338656630303234336334313937323537393963366465356265
38646434616462326332643663376361376231613336326531643130636134633038613435653435
38356363316232336630633566363830303664646363393438373637306239343066376161666139
62396230323464386561386434383436633931373236623730636362616435613831633332326230
61633133343334646332663439656236646638353265666237323136316566323937623633303830
35303866303033313964636133356366323333353937353337623933623836393635653131666134
31383331346563636134303631316261383161323461643636376238373837663235363463346266
65343861313436636530616534613832666436376364623264393532303530356631336231643938
37336365663665343365386465643336303135626465343966303237656438343866386163376164
31393136623461363730656536623565323436356563656462346431313231623739393335326539
39363139643735623662663964653963326562633262323266316662313733376333626562613633
32643264373065336435
