---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "rtrox-io"
spec:
  secretName: "rtrox-io-tls"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "rtrox.io"
  dnsNames:
    - "rtrox.io"
    - "*.rtrox.io"
    - "*.chongus.rtrox.io"
